export const GET_SERIES = 'SERIES LIST';
export const GET_SERIES_START = 'GET SERIES START';
export const GET_SERIES_SUCCESS = 'GET SERIES SUCCESS';
export const GET_SERIES_FAILED = 'GET SERIES FAILED';

export const GET_GENRES = 'GENRES LIST';
export const GET_GENRES_START = 'GET GENRES START';
export const GET_GENRES_SUCCESS = 'GET GENRES SUCCESS';
export const GET_GENRES_FAILED = 'GET GENRES FAILED';

export const GET_LAST_MIX = 'GET LAST MIX';
export const UPDATE_LAST_MIX = 'UPDATE LAST MIX';

export const GET_CURRENT_MIX_FROM_PLAYER = 'GET CURRENT MIX FROM PLAYER ACTION';
export const SET_MIX_TO_PLAYER = 'SET MIX TO PLAYER ACTION';

export const ADD_MIX_TO_CONTAINER = 'ADD MIX TO CONTAINER ACTION';
export const REMOVE_MIX_FROM_CONTAINER = '[ACTION] -> REMOVE MIX FROM CONTAINER';

export const SET_AUDIO_ELEMENT = 'SET AUDIO ELEMENT';
export const GET_AUDIO_ELEMENT = 'GET AUDIO ELEMENT';
export const PLAY_AUDIO = 'PLAY AUDIO ACTION';
export const STOP_AUDIO = 'STOP AUDIO ACTION';
export const LOAD_AUDIO = 'LOAD AUDIO ACTION';
export const PAUSE_AUDIO = 'PAUSE AUDIO ACTION';

export const FETCH_TRACKS_OF_MIX = 'FETCH TRACKS OF MIX';

export const GET_CURRENT_TRACK = 'GET CURRENT TRACK ACTION';
export const SET_CURRENT_TRACK = 'SET CURRENT TRACK ACTION';
